AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A Lambda job that will snapshot all properly tagged instances, and
  automatically age older snapshots based on days of aging.
Resources:
  ebssnapshotlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        A Lambda job that will snapshot all properly tagged instances, and
        automatically age older snapshots based on days of aging.
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::999999999999:role/ebs_snapshot_lambda'
